epg:
  days: 2
  output_file: "epg.xml"
  # How often to refresh the EPG in the background, in hours.
  refresh_interval_hours: 12
  # Max videos to fetch per YouTube source. Lower for faster EPG generation.
  max_videos_per_source: 20

cache:
  ttl_hours: 12 # Default cache TTL in hours

publicity:
  general_ads:
    # Filter for ads between 15 seconds and 2 minutes
    min_duration: 15
    max_duration: 120
    cache: true
    cache_ttl_hours: 168 # 1 week
    youtube_channels:
      - "https://www.youtube.com/playlist?list=PL0E8CF42499A416D0"
      - "https://www.youtube.com/@publi456"
      - "https://www.youtube.com/@mamalucchettioficial"
      - "https://www.youtube.com/@piensamarketing"
      - "https://www.youtube.com/@quilmescerveza"

channels:
  - id: "news-channel"
    name: "Global News"
    group_title: "News"
    icon_url: "https://i.imgur.com/5zJ5z5Y.png"
    quality: "best[height<=360]"
    mixing_algorithm: "interleave"
    sort_order: "oldest"
    programs_per_publicity: 3
    publicity_pool: "general_ads"
    epg_refresh_strategy: 'rebuild' # Rebuild channel from scratch on every EPG refresh
    min_duration: 120
    max_duration: 1200
    output:
      resolution: "640x360"
      framerate: 30
      video_bitrate: "1M"
      audio_bitrate: "96k"
    youtube_channels:
      - "https://www.youtube.com/@BBCNews"
      - "https://www.youtube.com/@CNN"
      - "https://www.youtube.com/@AlJazeeraEnglish"

  - id: "tech-channel"
    name: "Tech Insights"
    group_title: "Technology"
    icon_url: "https://i.imgur.com/6gJ2z5Y.png"
    quality: "best[height<=1080]"
    mixing_algorithm: "concatenate"
    sort_order: "random"
    programs_per_publicity: 5
    publicity_pool: "general_ads"
    min_duration: 300
    max_duration: 1800
    output:
      resolution: "1920x1080"
      framerate: 30
      video_bitrate: "6M"
      audio_bitrate: "256k"
    youtube_channels:
      - "https://www.youtube.com/@mkbhd"
      - "https://www.youtube.com/@LinusTechTips"
      - "https://www.youtube.com/@UnboxTherapy"

  - id: "travel-channel"
    name: "World Explorer"
    group_title: "Travel"
    icon_url: "https://i.imgur.com/7zJ5z5Y.png"
    quality: "best[height<=720]"
    programs_per_publicity: 4
    publicity_pool: "general_ads"
    youtube_channels:
      - "https://www.youtube.com/@KaraandNate"
      - "https://www.youtube.com/@DrewBinsky"
      - "https://www.youtube.com/@TheEndlessAdventure"

  - id: "music-channel"
    name: "Music Mix"
    group_title: "Music"
    icon_url: "https://i.imgur.com/8zJ5z5Y.png"
    quality: "bestaudio"
    youtube_channels:
      - "https://www.youtube.com/@Vevo"

  - id: "80s-music-channel"
    name: "80s Music Hits"
    group_title: "Music"
    icon_url: "https://i.imgur.com/J5z5Y8z.png"
    quality: "best[height<=480]"
    mixing_algorithm: "interleave"
    sort_order: "random"
    programs_per_publicity: 5
    publicity_pool: "general_ads"
    output:
      resolution: "640x480"
      framerate: 30
      video_bitrate: "1.5M"
      audio_bitrate: "128k"
    youtube_channels:
      - "https://www.youtube.com/@FlashbackGrooves"
      - "https://www.youtube.com/@80sMusicHits63-w1f"
      - "https://www.youtube.com/playlist?list=PL-Q2AV9dPI_vb2vT_t22A4i3a-o1-B42B"
    cache: true # Enable caching for this channel
    cache_ttl_hours: 168 # 1 week

  - id: "shorts-channel"
    name: "Shorts"
    group_title: "Entertainment"
    icon_url: "https://i.imgur.com/9zJ5z5Y.png"
    quality: "best[height<=1080]"
    output:
      resolution: "1080x1920"
      framerate: 30
      video_bitrate: "4M"
      audio_bitrate: "128k"
    youtube_channels:
      - url: "https://www.youtube.com/@shootimpro"
        type: "shorts"
    match_title: "impro"
    date_after: "now-1y"
    cache: true # Enable caching for this channel
    cache_ttl_hours: 12 # Override global TTL for this channel

  - id: "mixed-media-channel"
    name: "Mixed Media"
    group_title: "Variety"
    youtube_channels:
      - "https://www.youtube.com/@mkbhd" # Defaults to type: videos
      - url: "https://www.youtube.com/@MrBeast"
        type: "shorts"
      - url: "https://www.youtube.com/playlist?list=PLrEnWoR732-BHrPp_P8G_geS_jK2vWd5u"
        type: "podcasts"